# Generated by Django 5.2.1 on 2025-05-22 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the food item', max_length=100)),
                ('calories', models.PositiveIntegerField(help_text='Number of calories in the food item')),
            ],
        ),
    ]
