# Generated by Django 5.2.1 on 2025-05-22 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditem',
            name='calories',
            field=models.PositiveIntegerField(help_text='Number of calories in the food'),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='name',
            field=models.CharField(help_text='Name of the food', max_length=100),
        ),
    ]
